# Generated by Django 3.2.12 on 2022-03-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='repeatUntil',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='repeat',
            field=models.CharField(choices=[('Never', 'Never'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Biweekly', 'Biweekly'), ('Monthly', 'Monthly')], default='Never', max_length=20),
        ),
    ]
